### PR TITLE
BE-50/add a function to compress image to 1mb

### PR DESCRIPTION
**Pull request by leksyking**
Linear link: https://linear.app/team-scale/issue/BE-50/create-function-to-compress-image

The function takes the image file
converts the image to PNG as the package used doesn't support all formats for compression
Resizes it to 1mb with the https://github.com/h2non/bimg package
Return the resized image as io.ReaderCloser which is the type of image passed into the mineserviceupload function

### CODE REVIEW

**Comment by kataszn** [comment]
You might have to upgrade it to return an image file instead of raw bytes.
looks good

**Comment by kataszn** [comment]
you're not receiving a filename, you're receiving a file object directly, please modify accordingly

**Comment by leksyking** [comment]
Thank you Usman, Kindly check again

**Comment by leksyking** [comment]
@zxenonx  @NwokoyeChigozie  @usmansadik  abeg help review the changes I made to the PR

**Comment by kataszn** [comment]
looks good

**Comment by kataszn** [comment]
the function should be exported though

**Comment by leksyking** [comment]
Okay I will capitalize it. Thanks

**Pull request merged**
