### PR TITLE
Feat/be 77 update user swagger docs

### PR DESCRIPTION
**Pull request by mikey247**
UPDATE USER SWAGGER DOCS
 Updated the swagger.json and swagger.yaml files with the update-user endpoint

**LINEAR TICKET**
https://linear.app/team-descripto/issue/BE-77/swagger-test-update-user-details-endpoint

### CODE REVIEW

**Comment by kataszn** [comment]
Looks good, but isn't this supposed to be one task?
because I can also see code to update user.

**Comment by mikey247** [comment]
Yeah, The update user code was just merged by @Emmrys-Jay, I don't know why the commit is showing here

**Comment by mikey247** [comment]
I think it's fine to merge, there are no conflicts with dev branch

**Comment by kataszn** [comment]
Sure, just trying to confirm.

**Pull request merged**
