### PR TITLE
Feat(BE-64): complete process batch api

### PR DESCRIPTION
**Pull request by emmrys-jay**
### Linear Ticket
https://linear.app/team-discripto/issue/BE-64/process-batch-api

### API Endpoint

- Accepts a JSON file and an optional CSV file.
- The Program determines from the JSON file if the CSV file is needed.
- If the JSON file contains a field with Image URLs, the handler proceeds.
- If the JSON file does not contain a field with Image URLs, the handler reverts to the CSV file.
- Parses the CSV file for valid image URLs
- Save a batch to the database.
- Begin a background process to process the image URLs
- Return a JSON response to the user indicating that the request has begun (see screenshot below).
- Notifies a user via email when the process has been completed.

#### Request
Screenshot from 2022-12-03 20-04-02

#### Response
Screenshot from 2022-12-03 19-22-59

#### JSON and CSV files
Screenshot from 2022-12-03 20-06-36

### CODE REVIEW

**Comment by kataszn** [comment]
Looks good, but you should not be returning the images field.
also the message is still set to "mine image successful", please modify accordingly.
I also think the **message** field inside the **data** field should be in the message field outside. like
```javascript
{
  "status": "success",
  "code": 200,
  "message": "process batch started",
  "data": {
    "id": "638b6bb437a213abb85cb306",
    "name": "APJKE",
    "description": "my batch collection for things to watch",
    "tags": [
      "anime",
      "movie",
      "POV"
    ],
    "status": "ongoing",
    "date_created": "2022-12-03T15:31:00.465342666Z"
  }
}
```

**Comment by emmrys-jay** [comment]
@usmansadik Thanks

Those have been fixed now.

**Comment by kataszn** [comment]
Ok sure

**Comment by kataszn** [comment]
Ok sure

**Pull request merged**
