### PR TITLE
feat(BE-51):Create endpoint to return a list of all mined-images in our API(admin)

### PR DESCRIPTION
**Pull request by noornee**
**ENDPOINT:**

- Created an endpoint to return all mined images to an admin user.
- Returns an object containing all the mined images created by a normal user

**LINEAR TICKET:**
- https://linear.app/team-scale/issue/BE-51/create-endpoint-to-return-a-list-of-all-mined-images-in-our-apiadmin

**Test Endpoint:**
to test my endpoint, you need to be logged in to get an access token.
send a post request to this http://44.211.169.234:9000/api/v1/login using this same exact user(johndoe)
i.e.
`curl http://44.211.169.234:9000/api/v1/login --json '{"email": "johndoe@email.com", "password": "password"}'`

this would return an object containg the access token.

then send a GET request to  http://44.211.169.234:9000/api/v1/admin/mined-images
i.e. 
```
curl http://44.211.169.234:9000/api/v1/admin/mined-images \
   -H "Accept: application/json" \
   -H "Authorization: Bearer {token}"
```
**NOTE:** this `{token}` is a placeholder so you need to replace it with the access token you got when you logged in

this would return alll the mined images present in our api

**PREVIEW:**
2022-11-25-081608_1883x434_scrot

2022-11-25-081733_1821x644_scrot

**NOTE:**
[jq](https://github.com/stedolan/jq) is a command line utility used to process json.
i just piped to it to make the output look better

### CODE REVIEW

**Comment by noornee** [comment]
@usmansadik  i'm done with the endpoint already but dont merge yet. i still havent implemented a function to check if the user has the right authorization token, i want to use this [function](https://github.com/workshopapps/pictureminer.api/blob/d0a22709b0c5b71c31f6fb4ff437d6f599a1256d/pkg/handler/mine-service/mine-service.go#L138)

is it okay for me to make it public?
[edit]: i also thing it should have its on package i.e token

**Comment by kataszn** [comment]
Surprisingly I made them public in my yet to be merged pr, damn.
Add them to the token.go file in the utility package.

**Comment by noornee** [comment]
alrightt, lemme do that!

**Comment by kataszn** [comment]
You done?

**Comment by noornee** [comment]
> You done?

yess i am

**Comment by kataszn** [comment]
ok, LGTM

**Pull request merged**
