### PR TITLE
Email Sending function

### PR DESCRIPTION
**Pull request by Adeben33**
Feat:BE-48-EmailFunction
This PR is to create the email service

### CODE REVIEW

**Comment by kataszn** [comment]
Resolve the merge conflicts.
Move your function to utility package

**Comment by emmrys-jay** [comment]
@Adeben33 Please check the message above.

Also, what version of a Golang are you using?

**Comment by Adeben33** [comment]
All conflicts are resolved

**Review by kataszn — COMMENTED** [review]
Looks good

**Pull request merged**
